Import('base_env')

base_env.Program('stepper_driver', ['main.c', 'hw_timer.c', 'command_layer.c', 'stepper_driver.c', 'udp.c', 'tcp.c', 'wifi.c', 'op_queue.c', 'jsmn.c'])
base_env.Program('quad_servo_driver', ['main.c', 'hw_timer.c', 'command_layer.c', 'quad_servo_driver.c', 'udp.c', 'tcp.c', 'wifi.c', 'quad_op_queue.c', 'jsmn.c'])
