Import('base_env')

quad_queue = base_env.Clone();
quad_queue.Append(CCFLAGS = ['-DMOTOR_COUNT=4'])
quad_queue.Object(source = 'op_queue.c', target = 'quad_op_queue.o')

stepper_queue = base_env.Clone();
stepper_queue.Append(CCFLAGS = ['-DMOTOR_COUNT=1'])
stepper_queue.Object(source = 'op_queue.c', target = 'stepper_op_queue.o')

base_env.Program('stepper_driver', ['main.c', 'hw_timer.c', 'command_layer.c', 'stepper_driver.c', 'udp.c', 'tcp.c', 'wifi.c', 'stepper_op_queue.o', 'jsmn.c'])
base_env.Program('quad_servo_driver', ['main.c', 'hw_timer.c', 'command_layer.c', 'quad_servo_driver.c', 'udp.c', 'tcp.c', 'wifi.c', 'quad_op_queue.o', 'jsmn.c'])
